spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wiki_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  web:
    resources:
      static-locations: classpath:/static/, classpath:/static/html/
logging:
  level:
    root: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID} --- [%15.15t] %-40.40logger{39} : %m%n%wEx"
  file:
    path: logs/
    name: info.log
  logback:
    rollingpolicy:
      max-file-size: 500MB
      max-history: 1
  server:
    port: 8080